// AUTO-GENERATED by scripts/sync-mock-photos.mjs — DO NOT EDIT BY HAND.
// Drop your photos in:
//   public/mock/photos/   (any names — used in alphabetical order)
//   public/mock/events/<event-code>.{jpg,png,webp,…}  (one per event)
// Then run `npm run sync-mocks` (auto-runs on dev/build/deploy).

export const PHOTO_FILES = [
  "6ea8ccdb1f1017299accc9f86d856ab9.jpg",
  "72d51735a2b3-491274358185115202540473477922639182623200782n.jpg",
  "Coachella-Outfits-Men.jpg",
  "Flowy Top and Distressed Jeans Coachella Outfits Men -dyluxe.jpg",
  "Flowy Top and Pants Coachella Outfits Men -la_hai.jpg",
  "Flowy Top and Shorts Coachella Outfits Men -eltonpigg.jpg",
  "Flowy Top and Shorts Coachella Outfits Men -the_alshoeholic.jpg",
  "Hawaiian-Shirt-and-Pants-Coachella-Outfits-Men-viro.men_-768x952.jpg",
  "Sleeveless Tops and Pants Coachella Outfits Men -maurorja.jpg",
  "WhatsApp-Image-2026-02-09-at-10.50.10-PM.jpeg",
  "alessandra-ambrosio-coachella-1482436447-643ef060778cc.avif",
  "hbz-coachella-.jpg",
  "images.jpeg",
  "otxbmyj88f5f1.jpeg"
] as const;

export const EVENT_FILES: Record<string, string> = {};
